### ISSUE TITLE
Everyone injection

### ISSUE THREAD

**Issue by localcc** [TheBunnies/TiktokUploaderBot#2]
If you ping everyone or any other role that you are not supposed to be pinging in your original message, the bot will ping it when reuploading.

**Comment by TheBunnies** [comment]
Good evening.

Thanks for noting this problem. I've fixed the issue and now the bot won't resend role mentions and everyone pings but you can still ping channels and individual users. 

The commit for this fix is: 303aa2800913d38e8645f08ccbbb4fa6aa55966c
